%% MAPAS
%
grd1='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD/croco_grd.nc.3';
his1='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD/croco_his.nc.3';
IJ=[53 84];
bio1=1; %NPZD
%bio=2; %PISCES
[MAPASPROM_NPZD_SIN_RIOS,SERIES_NPZD_SIN_RIOS]=PROMDIARIO_SERIES_J2(grd1,his1,IJ,bio1);
%
grd2='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD_RIOS/croco_grd.nc.3';
his2='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD_RIOS/croco_his.nc.3';
IJ=[53 84];
bio2=1; %NPZD
%bio=2; %PISCES
[MAPASPROM_NPZD_CON_RIOS,SERIES_NPZD_CON_RIOS]=PROMDIARIO_SERIES_J2(grd2,his2,IJ,bio2);
%
grd3='/data4/matlab/USIPA/Johnson2_PISCES_PRON_v1p3/CROCO_FILES/croco_grd.nc.3';
his3='/data4/matlab/USIPA/Johnson2_PISCES_PRON_v1p3/CROCO_FILES/croco_his.nc.3';
IJ=[53 84];
%bio=1; %NPZD
bio3=2; %PISCES
[MAPASPROM_PISCES_SIN_RIOS,SERIES_PISCES_SIN_RIOS]=PROMDIARIO_SERIES_J2(grd3,his3,IJ,bio3);
%%
save('MAPAS_PROM_UV_TS_O2_CHLA.mat','MAPASPROM_NPZD_CON_RIOS',...
    'MAPASPROM_NPZD_SIN_RIOS','MAPASPROM_PISCES_SIN_RIOS');
%
save('SERIES_J2_NM_UV_TS_O2_CHLA.mat','SERIES_NPZD_CON_RIOS',...
    'SERIES_NPZD_SIN_RIOS','SERIES_PISCES_SIN_RIOS');