%% MAPAS PROMEDIOS DIARIOS
%
function [MAPASPROM,SERIES]=PROMDIARIO_SERIES_J2(grd3,his3,IJ,bio)
start
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DIRECCIONES DE LOS ARCHIVOS %
%
%grd3='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD/croco_grd.nc.3';
%his3='/data4/matlab/USIPA/JOHNSON2_PRUEBAS/NPZD/croco_his.nc.3';
%nombre='NPZD_SIN_RIOS';
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% VARIABLES A ANALIZAR %%%%%
%
% bio = 1 NPZD
% bio = 2 PISCES
N=42;
T='temp';
S='salt';
U='u';
V='v';
CHL='CHLA';
NCHL='NCHL';
DCHL='DCHL';
NO3='NO3';
O2='O2';
PHT='PHYTO';
ZOO='ZOO';
ng=netcdf(grd3);
    lat=ng{'lat_rho'}(:);
    lon=ng{'lon_rho'}(:);
    mask=ng{'mask_rho'}(:);
close(ng)
mask(mask==0)=NaN;
%%
[day,~,year,imonth,~]=get_date(his3,1,2000);
%
tiempo=ncread(his3,'time');
for i=1:length(tiempo)
    t(i,1)=datenum(year,imonth,day,i-1,0,0);
end
if bio==1
    for i=1:length(tiempo)
        %SUPERFICIE
        [~,~,~,spdm(:,:,i,1)]=get_speed(his3,grd3,i,N,1);
    %
        um(:,:,i,1)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,N,'u'));
        vm(:,:,i,1)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,N,'v'));
        Tm(:,:,i,1)=get_hslice(his3,grd3,T,...
                    i,N,'r');
        Sm(:,:,i,1)=get_hslice(his3,grd3,S,...
                    i,N,'r');
        O2m(:,:,i,1)=get_hslice(his3,grd3,O2,...
                    i,N,'r');            
        CHLm(:,:,i,1)=get_hslice(his3,grd3,CHL,...
                    i,N,'r');
    %5m
        [~,~,~,spdm(:,:,i,2)]=get_speed(his3,grd3,i,-5,1);
    %
        um(:,:,i,2)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-5,'u'));
        vm(:,:,i,2)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-5,'v'));
        Tm(:,:,i,2)=get_hslice(his3,grd3,T,...
                    i,-5,'r');
        Sm(:,:,i,2)=get_hslice(his3,grd3,S,...
                    i,-5,'r');
        O2m(:,:,i,2)=get_hslice(his3,grd3,O2,...
                    i,-5,'r');
        CHLm(:,:,i,2)=get_hslice(his3,grd3,CHL,...
                    i,-5,'r');
    % 10m
        [~,~,~,spdm(:,:,i,3)]=get_speed(his3,grd3,i,-10,1);
    %
        um(:,:,i,3)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-10,'u'));
        vm(:,:,i,3)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-10,'v'));
        Tm(:,:,i,3)=get_hslice(his3,grd3,T,...
                    i,-10,'r');
        Sm(:,:,i,3)=get_hslice(his3,grd3,S,...
                    i,-10,'r');
        O2m(:,:,i,3)=get_hslice(his3,grd3,O2,...
                    i,-10,'r');
        CHLm(:,:,i,3)=get_hslice(his3,grd3,CHL,...
                    i,-10,'r');
    % 15m
        [~,~,~,spdm(:,:,i,4)]=get_speed(his3,grd3,i,-15,1);
    %
        um(:,:,i,4)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-15,'u'));
        vm(:,:,i,4)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-15,'v'));
        Tm(:,:,i,4)=get_hslice(his3,grd3,T,...
                    i,-15,'r');
        Sm(:,:,i,4)=get_hslice(his3,grd3,S,...
                    i,-15,'r');
        O2m(:,:,i,4)=get_hslice(his3,grd3,O2,...
                    i,-15,'r');
        CHLm(:,:,i,4)=get_hslice(his3,grd3,CHL,...
                    i,-15,'r');
    % 20m
        [~,~,~,spdm(:,:,i,5)]=get_speed(his3,grd3,i,-20,1);
    %
        um(:,:,i,5)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-20,'u'));
        vm(:,:,i,5)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-20,'v'));
        Tm(:,:,i,5)=get_hslice(his3,grd3,T,...
                    i,-20,'r');
        Sm(:,:,i,5)=get_hslice(his3,grd3,S,...
                    i,-20,'r');
        O2m(:,:,i,5)=get_hslice(his3,grd3,O2,...
                    i,-20,'r');
        CHLm(:,:,i,5)=get_hslice(his3,grd3,CHL,...
                    i,-20,'r');
    end
else
    for i=1:length(tiempo)
    %SUPERFICIE
        [~,~,~,spdm(:,:,i,1)]=get_speed(his3,grd3,i,N,1);
    %
        um(:,:,i,1)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,N,'u'));
        vm(:,:,i,1)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,N,'v'));
        Tm(:,:,i,1)=get_hslice(his3,grd3,T,...
                    i,N,'r');
        Sm(:,:,i,1)=get_hslice(his3,grd3,S,...
                    i,N,'r');
        O2m(:,:,i,1)=get_hslice(his3,grd3,O2,...
                    i,N,'r');
        DCHLm(:,:,i,1)=get_hslice(his3,grd3,DCHL,...
                    i,N,'r');
        NCHLm(:,:,i,1)=get_hslice(his3,grd3,NCHL,...
                    i,N,'r');
    %5m
        [~,~,~,spdm(:,:,i,2)]=get_speed(his3,grd3,i,-5,1);
    %
        um(:,:,i,2)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-5,'u'));
        vm(:,:,i,2)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-5,'v'));
        Tm(:,:,i,2)=get_hslice(his3,grd3,T,...
                    i,-5,'r');
        Sm(:,:,i,2)=get_hslice(his3,grd3,S,...
                    i,-5,'r');
        O2m(:,:,i,2)=get_hslice(his3,grd3,O2,...
                    i,-5,'r');
        DCHLm(:,:,i,2)=get_hslice(his3,grd3,DCHL,...
                    i,-5,'r');
        NCHLm(:,:,i,2)=get_hslice(his3,grd3,NCHL,...
                    i,-5,'r');
    % 10m
        [~,~,~,spdm(:,:,i,3)]=get_speed(his3,grd3,i,-10,1);
    %
        um(:,:,i,3)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-10,'u'));
        vm(:,:,i,3)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-10,'v'));
        Tm(:,:,i,3)=get_hslice(his3,grd3,T,...
                    i,-10,'r');
        Sm(:,:,i,3)=get_hslice(his3,grd3,S,...
                    i,-10,'r');
        O2m(:,:,i,3)=get_hslice(his3,grd3,O2,...
                    i,-10,'r');
        DCHLm(:,:,i,3)=get_hslice(his3,grd3,DCHL,...
                    i,-10,'r');
        NCHLm(:,:,i,3)=get_hslice(his3,grd3,NCHL,...
                    i,-10,'r');
    % 15m
        [~,~,~,spdm(:,:,i,4)]=get_speed(his3,grd3,i,-15,1);
    %
        um(:,:,i,4)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-15,'u'));
        vm(:,:,i,4)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-15,'v'));
        Tm(:,:,i,4)=get_hslice(his3,grd3,T,...
                    i,-15,'r');
        Sm(:,:,i,4)=get_hslice(his3,grd3,S,...
                    i,-15,'r');
        O2m(:,:,i,4)=get_hslice(his3,grd3,O2,...
                    i,-15,'r');
        DCHLm(:,:,i,4)=get_hslice(his3,grd3,DCHL,...
                    i,-15,'r');
        CHLm(:,:,i,4)=get_hslice(his3,grd3,NCHL,...
                    i,-15,'r');
    % 20m
        [~,~,~,spdm(:,:,i,5)]=get_speed(his3,grd3,i,-20,1);
    %
        um(:,:,i,5)=u2rho_2d(get_hslice(his3,grd3,U,...
                    i,-20,'u'));
        vm(:,:,i,5)=v2rho_2d(get_hslice(his3,grd3,V,...
                    i,-20,'v'));
        Tm(:,:,i,5)=get_hslice(his3,grd3,T,...
                    i,-20,'r');
        Sm(:,:,i,5)=get_hslice(his3,grd3,S,...
                    i,-20,'r');
        O2m(:,:,i,5)=get_hslice(his3,grd3,O2,...
                    i,-20,'r');
      	DCHLm(:,:,i,5)=get_hslice(his3,grd3,DCHL,...
                    i,-20,'r');
       	NCHLm(:,:,i,5)=get_hslice(his3,grd3,NCHL,...
                    i,-20,'r');
    end
end
% VAR(lon,lat,t,nivel)
% niveles= 0m 5m 10m 15m 20m de prof
%%
%Latitude = -44.36274544161574;
%Longitude = -74.25833333333333;
%(84, 53) usando netcdf y no ncread
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% MAPAS PROMEDIO
%
if bio==1
    for i=1:fix(length(tiempo)/24)
        tprom(i,1)=datenum(year,imonth,day+(i-1));
        spdpromd(:,:,i,:)=mean(spdm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Upromd(:,:,i,:)=mean(um(:,:,(1:24)+24*(i-1),:),3).*mask;
        Vpromd(:,:,i,:)=mean(vm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Tpromd(:,:,i,:)=mean(Tm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Spromd(:,:,i,:)=mean(Sm(:,:,(1:24)+24*(i-1),:),3).*mask;
        O2promd(:,:,i,:)=mean(O2m(:,:,(1:24)+24*(i-1),:),3).*mask;
        CHLpromd(:,:,i,:)=mean(CHLm(:,:,(1:24)+24*(i-1),:),3).*mask;
    end
else
    for i=1:fix(length(tiempo)/24)
        tprom(i,1)=datenum(year,imonth,day+(i-1));
        spdpromd(:,:,i,:)=mean(spdm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Upromd(:,:,i,:)=mean(um(:,:,(1:24)+24*(i-1),:),3).*mask;
        Vpromd(:,:,i,:)=mean(vm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Tpromd(:,:,i,:)=mean(Tm(:,:,(1:24)+24*(i-1),:),3).*mask;
        Spromd(:,:,i,:)=mean(Sm(:,:,(1:24)+24*(i-1),:),3).*mask;
        O2promd(:,:,i,:)=mean(O2m(:,:,(1:24)+24*(i-1),:),3).*mask;
        DCHLpromd(:,:,i,:)=mean(DCHLm(:,:,(1:24)+24*(i-1),:),3).*mask;
        NCHLpromd(:,:,i,:)=mean(NCHLm(:,:,(1:24)+24*(i-1),:),3).*mask;
    end
end
% VAR(lon,lat,t,nivel)
% t = promedio dia 1 - 2 - 3 - 4
VARSA=[' Tiempo dias ';...
      ' Latitud  °N ';...
      ' Longitud °E ';...
      ' MAGVEL  m/s ';...
      ' U VEL   m/s ';...
      ' V VEL   m/s ';...
      ' Temp    °C  ';...
      ' Salt    PSU ';...
      'O2  mMolO2/m3';...
      'CHL  mgChl/m3';...
      'LonLatDiaProf';...
      ' t   datenum ';...
      '0-5-10-15-20m'];
VARSB=[' Tiempo dias ';...
      ' Latitud  °N ';...
      ' Longitud °E ';...
      ' MAGVEL  m/s ';...
      ' U VEL   m/s ';...
      ' V VEL   m/s ';...
      ' Temp    °C  ';...
      ' Salt    PSU ';...
      'O2  mMolO2/m3';...
      'DCHL mgChl/m3';...
      'NCHL mgChl/m3';...
      'LonLatDiaProf';...
      ' t   datenum ';...
      '0-5-10-15-20m'];
MAPASPROM{1,1}=tprom;
MAPASPROM{1,2}=lat;
MAPASPROM{1,3}=lon;
MAPASPROM{1,4}=spdpromd;
MAPASPROM{1,5}=Upromd;
MAPASPROM{1,6}=Vpromd;
MAPASPROM{1,7}=Tpromd;
MAPASPROM{1,8}=Spromd;
MAPASPROM{1,9}=O2promd;
if bio==1
    MAPASPROM{1,10}=CHLpromd;
    MAPASPROM{1,11}=VARSA;
else
    MAPASPROM{1,10}=DCHLpromd + NCHLpromd;
    MAPASPROM{1,11}=VARSA;
%    MAPASPROM{1,12}=VARSB;
end
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% SERIES DE TIEMPO
% (84, 53) usando netcdf y no ncread
ng=netcdf(his3);
    NM=ng{'zeta'}(:);
close(ng)
%
if bio==1
    for i=1:5 % 5 niveles 0 5 10 15 20m
        spd_J2(i,:)=squeeze(spdm(IJ(1),IJ(2),:,i));
        u_J2(i,:)=squeeze(um(IJ(1),IJ(2),:,i));
        v_J2(i,:)=squeeze(um(IJ(1),IJ(2),:,i));
        T_J2(i,:)=squeeze(Tm(IJ(1),IJ(2),:,i));
        S_J2(i,:)=squeeze(Sm(IJ(1),IJ(2),:,i));
        O2_J2(i,:)=squeeze(O2m(IJ(1),IJ(2),:,i));
        CHL_J2(i,:)=squeeze(CHLm(IJ(1),IJ(2),:,i));
    end
else
    for i=1:5
        spd_J2(i,:)=squeeze(spdm(IJ(1),IJ(2),:,i));
        u_J2(i,:)=squeeze(um(IJ(1),IJ(2),:,i));
        v_J2(i,:)=squeeze(um(IJ(1),IJ(2),:,i));
        T_J2(i,:)=squeeze(Tm(IJ(1),IJ(2),:,i));
        S_J2(i,:)=squeeze(Sm(IJ(1),IJ(2),:,i));
        O2_J2(i,:)=squeeze(O2m(IJ(1),IJ(2),:,i));
        DCHL_J2(i,:)=squeeze(DCHLm(IJ(1),IJ(2),:,i));
        NCHL_J2(i,:)=squeeze(NCHLm(IJ(1),IJ(2),:,i));
    end
end
NM_J2(1,:)=squeeze(NM(:,IJ(1),IJ(2)));
%
VARSa=[' Tiempo  hrs ';...
      ' Nivel Mar m ';...
      ' MAGVEL  m/s ';...
      ' U VEL   m/s ';...
      ' V VEL   m/s ';...
      ' Temp    °C  ';...
      ' Salt    PSU ';...
      'O2  mMolO2/m3';...
      'CHL  mgChl/m3';...
      ' t   datenum ';...
      '0-5-10-15-20m'];
VARSb=[' Tiempo  hrs ';...
      ' Nivel Mar m ';...
      ' MAGVEL  m/s ';...
      ' U VEL   m/s ';...
      ' V VEL   m/s ';...
      ' Temp    °C  ';...
      ' Salt    PSU ';...
      'O2  mMolO2/m3';...
      'DCHL mgChl/m3';...
      'NCHL mgChl/m3';...
      ' t   datenum ';...
      '0-5-10-15-20m'];
SERIES{1,1}=t;
SERIES{1,2}=NM_J2;
SERIES{1,3}=spd_J2;
SERIES{1,4}=u_J2;
SERIES{1,5}=v_J2;
SERIES{1,6}=T_J2;
SERIES{1,7}=S_J2;
SERIES{1,8}=O2_J2;
if bio==1
    SERIES{1,9}=CHL_J2;
    SERIES{1,10}=VARSa;
else
    SERIES{1,9}=DCHL_J2+NCHL_J2;
    SERIES{1,10}=VARSa;
    %SERIES{1,11}=VARSb;
end
end




